## LISTA DE EXERCÍCIOS
## BIBLIOTECA NUMPY


In [31]:
#1-Converta os elementos do array [3, 5, 9, 16, 25] para float.
import numpy as np

array_float = np.array([3, 5, 9, 16, 25], dtype = np.float64)
print(array_float)

[ 3.  5.  9. 16. 25.]


In [20]:
#2-Dado o array [1.2, -3.6, 8.99999, 16.1], converta os seus elementos para int.
array_int = np.array([1.2, -3.6, 8.99999, 16.1], dtype = np.int32)
print(array_int)

[ 1 -3  8 16]


In [37]:
#3-Crie uma matriz 3x9 contendo apenas elementos com valor zero.
matriz_int = np.zeros([3, 9], dtype = np.int32)
print(matriz_zero_int)

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


In [45]:
#Crie uma matriz 6x7 de números inteiros contendo elementos com valor 1.
matriz_one_int = np.ones([6, 7], dtype = np.int32)
print(matriz_one_int)

[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


In [49]:
#5-Crie uma matriz identidade de tamanho 4.
matriz_5 = np.eye(4)
print(matriz_5)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [53]:
#6-Crie um array de números aleatórios entre 0 e 1 de tamanho 5.
array_6 = np.random.random(5)
print(array_6)

[0.06405985 0.66174994 0.72629407 0.06481335 0.82017688]


In [73]:
#7-Crie uma matriz 3x6 contendo números aleatórios de 0 a 5 (0, 1, 2, 3, 4, 5).
matriz_7 = np.random.randint(6, size = (3,6)) 
print(matriz_7)

[[2 0 2 0 3 1]
 [3 1 1 4 5 4]
 [5 5 2 1 4 1]]
